apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow
  namespace: wisecow
  labels:
    app: wisecow
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: wisecow.127.0.0.1.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wisecow
            port:
              number: 80
